"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";

export default function LoginPage() {
  const router = useRouter(); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setLoading(true); setError(""); try { const response = await fetch("/api/auth/login", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email, password }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error?.message || "Login gagal"); router.push("/"); router.refresh(); } catch (value) { setError(value instanceof Error ? value.message : "Login gagal"); } finally { setLoading(false); } };
  return <main className="auth-page"><section className="auth-card"><div className="brand"><div className="brand-mark">DK</div><div><span className="brand-name">DapurKasir</span><span className="brand-sub">operasional kuliner</span></div></div><div className="auth-heading"><p className="eyebrow">Selamat datang kembali</p><h1>Masuk ke ruang kerja</h1><p>Kelola penjualan, produksi, dan laba usaha dalam satu tempat.</p></div><form onSubmit={submit} className="auth-form"><div className="field"><label htmlFor="email">Email usaha</label><input className="input" id="email" type="email" value={email} onChange={(event) => setEmail(event.target.value)} required placeholder="nama@usaha.com" /></div><div className="field"><label htmlFor="password">Password</label><input className="input" id="password" type="password" value={password} onChange={(event) => setPassword(event.target.value)} required minLength={8} placeholder="Minimal 8 karakter" /></div>{error && <div className="callout error">{error}</div>}<button className="button button-primary" style={{ width: "100%" }} disabled={loading}>{loading ? "Memeriksa..." : "Masuk"}</button></form><p className="auth-foot">Belum punya akun? <a href="/register">Buat akun owner</a> · <a href="/pricing">Lihat harga</a></p></section></main>;
}
