db-uri = "postgres://dapurkasir:change-me@postgres:5432/dapurkasir"
db-schema = "public"
db-anon-role = "anon"
jwt-secret = "change-this-to-a-long-random-secret-at-least-32-chars"
server-port = 3001
max-rows = 1000
pre-request = "public.check_request"
