"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";

export default function RegisterPage() {
  const router = useRouter(); const [form, setForm] = useState({ name: "", email: "", business_name: "", password: "", confirm: "" }); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  const update = (key: keyof typeof form, value: string) => setForm((current) => ({ ...current, [key]: value }));
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setError(""); if (form.password !== form.confirm) return setError("Konfirmasi password belum sama."); setLoading(true); try { const response = await fetch("/api/auth/register", { method: "POST", credentials: "same-origin", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...form, confirm: undefined }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error?.message || "Registrasi gagal"); router.push("/"); router.refresh(); } catch (value) { setError(value instanceof Error ? value.message : "Registrasi gagal"); } finally { setLoading(false); } };
  return <main className="auth-page"><section className="auth-card"><div className="brand"><div className="brand-mark">DK</div><div><span className="brand-name">DapurKasir</span><span className="brand-sub">operasional kuliner</span></div></div><div className="auth-heading"><p className="eyebrow">Mulai lebih rapi</p><h1>Buat akun usaha</h1><p>Setup awal gratis. Satuan standar dan dashboard langsung siap dipakai.</p></div><form onSubmit={submit} className="auth-form"><div className="field"><label htmlFor="name">Nama owner</label><input className="input" id="name" value={form.name} onChange={(event) => update("name", event.target.value)} required placeholder="Nama kamu" /></div><div className="field"><label htmlFor="business_name">Nama usaha</label><input className="input" id="business_name" value={form.business_name} onChange={(event) => update("business_name", event.target.value)} required placeholder="Contoh: Dapur Sari Nusantara" /></div><div className="field"><label htmlFor="email">Email usaha</label><input className="input" id="email" type="email" value={form.email} onChange={(event) => update("email", event.target.value)} required placeholder="nama@usaha.com" /></div><div className="form-grid"><div className="field"><label htmlFor="password">Password</label><input className="input" id="password" type="password" value={form.password} onChange={(event) => update("password", event.target.value)} required minLength={8} /></div><div className="field"><label htmlFor="confirm">Konfirmasi</label><input className="input" id="confirm" type="password" value={form.confirm} onChange={(event) => update("confirm", event.target.value)} required minLength={8} /></div></div>{error && <div className="callout error">{error}</div>}<button className="button button-primary" style={{ width: "100%" }} disabled={loading}>{loading ? "Membuat akun..." : "Buat akun gratis"}</button></form><p className="auth-foot">Sudah punya akun? <a href="/login">Masuk di sini</a> · <a href="/pricing">Lihat harga</a></p></section></main>;
}
